<h1 align="center">Hi ğŸ‘‹, I'm Renato Margoni</h1>
<h3 align="center">A business intelligence analyst from Brazil</h3>

- ğŸ”­ Iâ€™m currently working on [Talent Marcel](https://talentmarcel.com.br/)

- ğŸŒ± Iâ€™m currently learning **Phyton** and **Data Science**

- ğŸ‘¨â€ğŸ’» All of my projects are available at [https://www.linkedin.com/in/renato-margoni/](https://www.linkedin.com/in/renato-margoni/)

- ğŸ’¬ Ask me about **Data Visualization, Data Marketing, Web Anlytics and Business Intelligence**

- ğŸ“« How to reach me **adm.margoni@gmail.com** Fone number: **+55 11 99257-1266**

- âš¡ Another Skills that i have **Power Bi**, **Locker Studio/DataStudio**, **Power Point**, **Excel**, **Google Analytics**, **Facebook Ads**, **Google Ads** and **more...**

<h3 align="left">Connect with me:</h3>
<p align="left">
<a href="mailto: adm.margoni@gmail.com"
  <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Gmail_icon_(2020).svg/" width="30" /></a>
<a href="https://linkedin.com/in/renato-margoni" target="blank">
  <img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" alt="renato-margoni" height="30" width="40" /></a>

<a href="https://instagram.com/remargoni" target="blank">
  <img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/instagram.svg" alt="remargoni" height="30" width="40" /></a>
</p>

<h3 align="left">Languages and Tools:</h3>
<p align="left"> <a href="https://www.microsoft.com/en-us/sql-server" target="_blank" rel="noreferrer"> 
  <img src="https://www.svgrepo.com/show/303229/microsoft-sql-server-logo.svg" alt="mssql" width="40" height="40"/> </a> 
<a href="https://www.mysql.com/" target="_blank" rel="noreferrer"> 
  <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg" alt="mysql" width="40" height="40"/> </a> 
<a href="https://www.photoshop.com/en" target="_blank" rel="noreferrer"> 
  <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/photoshop/photoshop-line.svg" alt="photoshop" width="40" height="40"/> </a> 
<a href="https://www.python.org" target="_blank" rel="noreferrer"> 
  <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg" alt="python" width="40" height="40"/> </a> 
<a href="https://www.sqlite.org/" target="_blank" rel="noreferrer"> 
  <img src="https://www.vectorlogo.zone/logos/sqlite/sqlite-icon.svg" alt="sqlite" width="40" height="40"/> </a> 
<a href="https://www.adobe.com/products/xd.html" target="_blank" rel="noreferrer"> 
  <img src="https://cdn.worldvectorlogo.com/logos/adobe-xd.svg" alt="xd" width="40" height="40"/> </a> 
</p>

<p><img align="center" src="https://github-readme-streak-stats.herokuapp.com/?user=remargoni&" alt="remargoni" /></p>
